name: Maven Build

# Run workflow for any push to a branch
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

# Only permit one build per branch/tag
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}

jobs:
  maven-build:
    uses: Telicent-oss/shared-workflows/.github/workflows/maven.yml@main
    with:
      # No SNAPSHOT publishing
      PUBLISH_SNAPSHOTS: false
      RELEASE_FILES: "**/*-distribution-*"
    secrets: inherit
