name: Action Self-Tests

# Run workflow for any push to a branch
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch:

# Only permit one build per branch/tag
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}

jobs:
  passing-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Maven Build
        run: |
          cd src/it/fixed-vulnerability
          mvn --batch-mode clean install

      - name: Maven Trivy Scan
        id: trivy
        continue-on-error: true
        uses: Telicent-io/maven-trivy-scan-action@v1
        with:
          pattern: "*-bom.json"
          directory: src/it/fixed-vulnerability

      - name: Ensure Trivy Scan Step Succeeded
        if: ${{ steps.trivy.outcome != 'success' }}
        run: |
          echo "Trivy Scanning Step failed unexpectedly"
          exit 1

  failing-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Maven Build
        run: |
          cd src/it/known-vulnerability
          mvn --batch-mode clean install

      - name: Maven Trivy Scan
        id: trivy
        continue-on-error: true
        uses: Telicent-io/maven-trivy-scan-action@v1
        with:
          pattern: "*-bom.json"
          directory: src/it/known-vulnerability

      - name: Ensure Trivy Scan Step Failed
        if: ${{ steps.trivy.outcome == 'success' }}
        run: |
          echo "Trivy Scanning Step DID NOT fail as expected"
          exit 1
